
package com.mycompany.crud;
import java.io.File;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.lang.NumberFormatException;
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLNombre = new javax.swing.JLabel();
        jLNumero = new javax.swing.JLabel();
        jTNombre = new javax.swing.JTextField();
        jTNumero = new javax.swing.JTextField();
        jBCrear = new javax.swing.JButton();
        jBLeer = new javax.swing.JButton();
        jBActualizar = new javax.swing.JButton();
        jBBorrar = new javax.swing.JButton();
        jBLimpiar = new javax.swing.JButton();
        Aviso = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLNombre.setText("Nombre:");

        jLNumero.setText("Numero:");

        jTNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNombreActionPerformed(evt);
            }
        });

        jBCrear.setText("Crear");
        jBCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCrearActionPerformed(evt);
            }
        });

        jBLeer.setText("Leer");
        jBLeer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLeerActionPerformed(evt);
            }
        });

        jBActualizar.setText("Actualizar");
        jBActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBActualizarActionPerformed(evt);
            }
        });

        jBBorrar.setText("Borrar");
        jBBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBorrarActionPerformed(evt);
            }
        });

        jBLimpiar.setText("Limpiar");
        jBLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarActionPerformed(evt);
            }
        });

        Aviso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AvisoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLNumero, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLNombre, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTNumero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jBCrear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBLeer)
                .addGap(18, 18, 18)
                .addComponent(jBActualizar)
                .addGap(18, 18, 18)
                .addComponent(jBBorrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBLimpiar)
                .addGap(0, 30, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(Aviso, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNombre)
                    .addComponent(jTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNumero)
                    .addComponent(jTNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCrear)
                    .addComponent(jBLeer)
                    .addComponent(jBActualizar)
                    .addComponent(jBBorrar)
                    .addComponent(jBLimpiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Aviso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNombreActionPerformed

    private void jBCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCrearActionPerformed
        try {

            String newName = String.valueOf(jTNombre.getText());

            long newNumber = Long.parseLong(jTNumero.getText());

            String nameNumberString;
            String name;
            long number;
            int index;

            File file = new File("C:\\Users\\Usuario\\Documents\\NetBeansProjects\\CRUD\\src\\main\\java\\com\\mycompany\\crud.txt");

            if (!file.exists()) {

                file.createNewFile();
            }

            RandomAccessFile raf = new RandomAccessFile(file, "rw");
            boolean found = false;

            while (raf.getFilePointer() < raf.length()) {

                nameNumberString = raf.readLine();

                String[] lineSplit = nameNumberString.split("!");

                name = lineSplit[0];
                number = Long.parseLong(lineSplit[1]);

                if (name.equals(newName) || number == newNumber) {
                    found = true;
                    break;
                }
            }

            if (found == false) {

                nameNumberString = newName + "!" + String.valueOf(newNumber);

                raf.writeBytes(nameNumberString);

                raf.writeBytes(System.lineSeparator());

                Aviso.setText(" Amigo agregado. ");

                raf.close();
            } else {

                raf.close();

                Aviso.setText(" El registro de  " + newName + " no existe. ");
            }
        } catch (IOException ioe) {

            System.out.println(ioe);
        } catch (NumberFormatException nef) {

            System.out.println(nef);
        }
    }//GEN-LAST:event_jBCrearActionPerformed

    private void jBLeerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLeerActionPerformed
 try {

            String nameNumberString;
            String name;
            String newName = String.valueOf(jTNombre.getText());
            long number;
            int index;

            
            File file = new File("C:\\Users\\Usuario\\Documents\\NetBeansProjects\\CRUD\\src\\main\\java\\com\\mycompany\\crud.txt");

            if (!file.exists()) {

                file.createNewFile();
            }


            RandomAccessFile raf = new RandomAccessFile(file, "rw");
            boolean found = false;


            while (raf.getFilePointer() < raf.length()) {


                nameNumberString = raf.readLine();


                String[] lineSplit = nameNumberString.split("!");

                name = lineSplit[0];
                number = Long.parseLong(lineSplit[1]);
                if (name.equals(newName)) {
                    Aviso.setText("Nombre y ID del amigo: " + name + " |" + number);
                }

            }
        } catch (IOException ioe) {
            System.out.println(ioe);
        } catch (NumberFormatException nef) {
            System.out.println(nef);
        } 
    }//GEN-LAST:event_jBLeerActionPerformed

    private void AvisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AvisoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AvisoActionPerformed

    private void jBActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBActualizarActionPerformed
try {
 

            String newName = String.valueOf(jTNombre.getText());
 

            long newNumber = Long.parseLong(jTNumero.getText());
 
            String nameNumberString;
            String name;
            long number;
            int index;
 

            File file = new File("C:\\Users\\Usuario\\Documents\\NetBeansProjects\\CRUD\\src\\main\\java\\com\\mycompany\\crud.txt");
 
            if (!file.exists()) {
 

                file.createNewFile();
            }

            RandomAccessFile raf = new RandomAccessFile(file, "rw");
            boolean found = false;
 

            while (raf.getFilePointer() < raf.length()) {
 

                nameNumberString = raf.readLine();
 
 
                String[] lineSplit = nameNumberString.split("!");
 
   
                name = lineSplit[0];
                number = Long.parseLong(lineSplit[1]);
 

                if (name.equals(newName) || number == newNumber) {
                    found = true;
                    break;
                }
            }
 

            if (found == true) {

                File tmpFile = new File("C:\\Users\\Usuario\\Documents\\NetBeansProjects\\CRUD\\src\\main\\java\\com\\mycompany\\crud.txt");
 

                RandomAccessFile tmpraf = new RandomAccessFile(tmpFile, "rw");

                raf.seek(0);
 

                while (raf.getFilePointer()< raf.length()) {
 

                    nameNumberString = raf.readLine();
 
                    index = nameNumberString.indexOf('!');
                    name = nameNumberString.substring(0, index);

                    if (name.equals(newName)) {
 
                        nameNumberString = name + "!"  + String.valueOf(newNumber);
                    }
 
                    tmpraf.writeBytes(nameNumberString);
 

                    tmpraf.writeBytes(System.lineSeparator());
                }
 

                raf.seek(0);
                tmpraf.seek(0);

                while (tmpraf.getFilePointer()< tmpraf.length()) {
                    raf.writeBytes(tmpraf.readLine());
                    raf.writeBytes(System.lineSeparator());
                }

                raf.setLength(tmpraf.length());
 

                tmpraf.close();
                raf.close();

                tmpFile.delete();
 
                Aviso.setText(" Amigo actualizado. ");
            }

            else {
 

                raf.close();

                Aviso.setText(" El registro de  "+newName+" no existe. ");
            }
        }
 
        catch (IOException ioe) {
            System.out.println(ioe);
        }
 
        catch (NumberFormatException nef) {
            System.out.println(nef);
        }
    }//GEN-LAST:event_jBActualizarActionPerformed

    private void jBBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBorrarActionPerformed
 try {
 

            String newName = String.valueOf(jTNombre.getText());
 
            String nameNumberString;
            String name;
            long number;
            int index;
 
            File file = new File("C:\\Users\\Usuario\\Documents\\NetBeansProjects\\CRUD\\src\\main\\java\\com\\mycompany\\crud.txt");
 
            if (!file.exists()) {
 

                file.createNewFile();
            }
 

            RandomAccessFile raf = new RandomAccessFile(file, "rw");
            boolean found = false;

            while (raf.getFilePointer() < raf.length()) {
 

                nameNumberString = raf.readLine();

                String[] lineSplit = nameNumberString.split("!");
 

                name = lineSplit[0];
                number = Long.parseLong(lineSplit[1]);
 

                if (name.equals(newName)== true) {
                    found = true;
                    break;
                }
            }
 

            if (found == true) {
 

                File tmpFile = new File("C:\\Users\\Usuario\\Documents\\NetBeansProjects\\CRUD\\src\\main\\java\\com\\mycompany\\crud.txt");
 

                RandomAccessFile tmpraf = new RandomAccessFile(tmpFile, "rw");
 

                raf.seek(0);
 

                while (raf.getFilePointer() < raf.length()) {
 

                    nameNumberString = raf.readLine();
 
                    index = nameNumberString.indexOf('!');
                    name = nameNumberString.substring(0, index);
 

                    if (name.equals(newName)==true) {
 

                        continue;
                    }
 
 
                    tmpraf.writeBytes(nameNumberString);
 

                    tmpraf.writeBytes(System.lineSeparator());
                }

                raf.seek(0);
                tmpraf.seek(0);
 

                while (tmpraf.getFilePointer()< tmpraf.length()) {
                    raf.writeBytes(tmpraf.readLine());
                    raf.writeBytes(System.lineSeparator());
                }

                raf.setLength(tmpraf.length());
 
                tmpraf.close();
                raf.close();
 

                tmpFile.delete();
 
                Aviso.setText("Amigo eliminado. ");
            }
 

            else {
 
                raf.close();
 

                Aviso.setText(" El registro de  "+newName+" no existe. ");
            }
        }
 
        catch (IOException ioe) {
            System.out.println(ioe);
        }
    }//GEN-LAST:event_jBBorrarActionPerformed

    private void jBLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarActionPerformed
    Aviso.setText("");
    jTNombre.setText("");
    jTNumero.setText("");
    }//GEN-LAST:event_jBLimpiarActionPerformed


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Aviso;
    private javax.swing.JButton jBActualizar;
    private javax.swing.JButton jBBorrar;
    private javax.swing.JButton jBCrear;
    private javax.swing.JButton jBLeer;
    private javax.swing.JButton jBLimpiar;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLNumero;
    private javax.swing.JTextField jTNombre;
    private javax.swing.JTextField jTNumero;
    // End of variables declaration//GEN-END:variables
}
